--- 
- name: Create a new database with name 'my-database'
  postgresql_db:
    login_host: "{{ login_host }}"
    login_user: "{{ login_username }}"
    login_password: "{{ login_password }}"
    name: "{{ database_name }}"
    port: "{{ port }}"
    state: "{{ state }}"

- name: Check DB connection
  community.postgresql.postgresql_script:
   login_user: "{{ login_username }}"
   login_password: "{{ login_password }}"
   login_host: "{{ login_host }}"
   port: "{{ port }}"
   db: "{{ database_name }}"
   path: "{{ path_to_script }}/{{ filename_to_execute }}"
