---
filename_to_execute: "table.sql"
login_username: "root"
login_password: "rootroot"
login_host: "my-postgres-db-instance1.chhlks3y2gpy.ap-south-1.rds.amazonaws.com"
database_name: "newdb"
path_to_script: "/home/ec2-user/Postgresql/psql-on-aws-rds/roles/createdb_and_executescript/files"
port: "5432"
state: "present"
